#!/bin/bash

GATEWAY="10.10.0.1"
BASE_IP="10.10."
TAGS="k3s,k8s,kubernetes,homelab,cluster,dev"

function create_and_start_vm() {
    qm clone --full --name "$1" 9011 $2
    qm disk resize $2 scsi0 32G
    qm set $2 --ipconfig0 "ip6=auto,ip=${BASE_IP}$3/24,gw=$4"
    qm set $2 --tags "$5"
    # qm start $2
}

for i in {210..215}; do
    create_and_start_vm "k3s-dev-master-$i" "$i" $i $GATEWAY "$TAGS"
done


# for i in {10210..10212}; do qm clone --full --name k3s-dev-master-$i 9011 $i; done
# for i in {10213..10215}; do qm clone --full --name k3s-dev-worker-$i 9011 $i; done
# for i in {10210..10215}; do qm disk resize $i scsi0 32G; done
# qm set 10210 --ipconfig0 "ip6=auto,ip=10.10.0.210/24,gw=10.10.0.1"
# qm set 10211 --ipconfig0 "ip6=auto,ip=10.10.0.211/24,gw=10.10.0.1"
# qm set 10212 --ipconfig0 "ip6=auto,ip=10.10.0.212/24,gw=10.10.0.1"
# qm set 10213 --ipconfig0 "ip6=auto,ip=10.10.0.213/24,gw=10.10.0.1"
# qm set 10214 --ipconfig0 "ip6=auto,ip=10.10.0.214/24,gw=10.10.0.1"
# qm set 10215 --ipconfig0 "ip6=auto,ip=10.10.0.215/24,gw=10.10.0.1"

# for i in {10210..10215}; do qm set $i --tags k3s,k8s,kubernets,homelab,cluster,dev; done
# for i in {10210..10215}; do qm start $i; done
